[package]
name = "fluxion"
license = "MIT OR Apache-2.0"
description = "Fluxion is an actor framework written in rust and designed for distributed systems."
repository = "https://github.com/peperworx/fluxion"
categories = ["concurrency"]
keywords = ["actor", "distributed", "async", "fluxion"]
readme = "README.md"
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
bincode = { version = "1.3.3", optional = true }
serde = { version = "1.0.164", features = ["derive"], optional = true }
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["rt", "rt-multi-thread", "sync", "macros"] }
tracing = { version = "0.1.37", optional = true }
tracing-subscriber = "0.3.17"

[features]
default = ["foreign", "notifications", "federated", "bincode"]
full = ["foreign", "notifications", "federated", "bincode", "tracing"]
# Enables serde support for messages
serde = ["dep:serde"]
bincode = ["serde", "dep:bincode"]
foreign = []
notifications = []
federated = []
tracing = ["dep:tracing"]

[[example]]
name = "foreign"

[package.metadata.cargo-feature-combinations]

# Exclude features from the feature combination matrix
denylist = ["default", "full"]
