site_name: Fluxion
theme:
  name: material
  logo: assets/fluxion_square.svg
  palette:
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode