site_name: Fluxion
theme:
  name: material
  logo: assets/fluxion_square.png
  favicon: assets/fluxion_square.png
  palette:
    - scheme: slate
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: default
      primary: deep orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate

repo_url: https://github.com/peperworx/fluxion
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
nav:
  - 'index.md'
  - 'Getting Started':
    - 'getting_started/index.md'
    - 'Defining an Executor': 'getting_started/executor.md'
    - 'Defining a Message Serializer': 'getting_started/serialization.md'
    - 'Initializing Fluxion': 'getting_started/initialization.md'