[package]
name = "ensure_fluxion_no_std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluxion = { path = "../" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"