[package]
name = "fluxion_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Fluxion internal crates
fluxion_message = { path = "../fluxion_message" }

# Cfg macro crates.
cfg-if = "1.0.0"