[package]
name = "fluxion_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "2.0.76", features=["extra-traits"] }

[lib]
proc-macro = true
